---
title: "draft"
author: "Yishak Ali"
date: "11/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(readxl)
library(gganimate)
library(formattable)
library(ztable)
library(magrittr)
library(condformat)
library(rstanarm)
library(patchwork)
library(ggthemes)
library(gt)
library(gtsummary)
library(broom.mixed)

```



```{r}
Us_premium <- read_excel("final_proj/US_premium_rd_costs.xlsx") %>% 
  clean_names() %>%
  mutate(Company = as.factor(company)) %>% 
  mutate(Id = 1:15)

# International price as a portion of US prices

Us_premium %>% 
  ggplot(aes(x = fct_reorder(company, international_price_us_price), 
             y = international_price_us_price, 
             fill = company)) +
    geom_col() +
    theme(axis.text.x = element_text(angle = 90)) +
    theme(legend.position = "none") +
    labs(title = "International Drug Prices as a Percentage of US Prices, 2015",
         subtitle = "US Price are consistently above International Prices",
         x = "Firms",
         y = "Percentage",
         caption = "Health Affairs Blog") +
    scale_y_continuous(labels = scales::percent_format()) +
    geom_hline(yintercept = mean(Us_premium$international_price_us_price),
               color = "blue")



Us_premium_2 <- Us_premium %>% 
  select(company, us_sales_2015_millions, revenue_from_us_premium) %>% 
  mutate(difference = us_sales_2015_millions - revenue_from_us_premium) %>% 
  mutate(premium_sales = revenue_from_us_premium/us_sales_2015_millions) %>%
  mutate(premium_sales = round(revenue_from_us_premium/us_sales_2015_millions, 2) * 100) %>% 
  pivot_longer(col = -c(company,us_sales_2015_millions, premium_sales), 
               names_to = "revenue_source", 
               values_to = "dollar_amount")

# US premium revenue as a portion of total US sales revenue

Us_premium_2 %>% 
  ggplot(aes(x = fct_reorder(company, dollar_amount), y = dollar_amount, fill = revenue_source)) +
    geom_col() +
    geom_label(data = Us_premium_2 %>% filter(revenue_source == "difference"), aes(label = premium_sales), size = 2) +
    theme(axis.text.x = element_text(angle = 90)) +
    scale_y_continuous(labels = scales::dollar_format()) +
    scale_fill_manual(name = "", values = c("dodgerblue", "coral"),
                      labels = c("Total US Sales", "Revenue from US Premium")) +
    labs(title = "Portion of Total US Sales Made Up by the US Premium in 2015",
         x = "Firms",
         y = "US Dollars (millions)")


Us_premium_select <- Us_premium %>% 
  select(company, us_sales_2015_millions, revenue_from_us_premium) %>% 
  filter(company == "Biogen") %>%
  mutate(difference = us_sales_2015_millions - revenue_from_us_premium) %>% 
  pivot_longer(col = -c(company, us_sales_2015_millions), 
               names_to = "revenue_source", 
               values_to = "dollar_amount") %>% 
  arrange(desc(revenue_source)) %>%
  mutate(prop = dollar_amount / sum(Us_premium_select$dollar_amount) *100) %>%
  mutate(ypos = cumsum(prop) - prop* .5)

# US premium revenue as a portion of total US sales revenue for individual firms; alternative to barplot?


Us_premium_select %>% 
  ggplot(aes(x= "", y = dollar_amount , fill = revenue_source)) +
    geom_bar(stat="identity", width = 1, color= "white") +
    coord_polar("y", start=0) +
    theme_void() +
  
   # Unsure how to get label positions right
  
    geom_text(aes(y = ypos, label = dollar_amount), color = "white", size=6)

# How much of the US premium is excess profits?

Us_premium %>% 
  ggplot(aes(x =fct_reorder(company, revenues_from_us_prmium_as_percent_of_global_research_and_development), 
             y = revenues_from_us_prmium_as_percent_of_global_research_and_development,
         fill = company)) +
    geom_col() +
    scale_y_continuous(labels = scales::percent_format()) +
    geom_hline(yintercept = 1, color = "#2E294E") +
    geom_hline(yintercept = mean(Us_premium$revenues_from_us_prmium_as_percent_of_global_research_and_development), 
               color = "#1B998B") +
    annotate("text", label = "1:1; fair ratio",
             x = 2.5, y = 1.15, 
             size = 3, color = "#2E294E") +
    annotate("text", label = "1.63:1; actual average ratio",
             x = 3, y = 1.75, 
             size = 3, color = "#1B998B") +
    theme(axis.text.x = element_text(angle = 90)) +
    theme(legend.position = "none") +
    labs(title = " Average 63% Difference Between US Premium Revenue and R&D Cost Needs, 2015",
         subtitle = "Pharmaceutical Firms are Making Excess Profits from US Premium at Expense of Patients",
         x = "Firms",
         y = "Percentage",
         caption = "Source: Health Affairs Blog") +
  theme(plot.title = element_text(size = 12.4))


# Spending per capita

spending_per_cap <- read.csv("spending_per-cap.csv") %>% 
    clean_names() %>% 
    select(location, time, value) %>% 
    rename(country_code = location)

oced_countries <- unique(spending_per_cap$location)
  


population_data <- read_excel("population_data.xls", skip = 3) %>% 
  clean_names() %>% 
  select(country_name, country_code, x2015:x2019) %>% 
  filter(country_code %in% oced_countries)

pop_spending <- full_join(spending_per_cap, population_data, by = "country_code") %>% 
  pivot_longer(cols = c(x2015, x2016, x2017), names_to = "year", 
               values_to = "population") %>% 
  select(-year)


pop_spending %>%  
  ggplot(aes(country_name, population), color = country_code) +
    geom_point(size = pop_spending$value *.005) +
    theme(axis.text.x = element_text(angle = 90)) +
    transition_states(time,
                    transition_length = 2,
                    state_length = 1)

g7_spending <- read_csv("final_proj/g7_spending_per_cap.csv") %>% 
  clean_names() %>% 
  select(location, time, value) %>% 
  rename(Country = location)

g7_spending %>% 
  ggplot(aes(time, value, color = Country)) +
    labs(title = "Phamaceutical Spending per Capita for G7 Countries, 1970 - 2019",
         subtitle = "The US's spending per capita is an outlier among similar wealthy, developed nations",
         x = "Year",
         y = "Spending per Capita in USD") +
    scale_y_continuous(labels = scales::dollar_format()) +
    geom_line() +
    geom_point() +
    transition_reveal(time)
  
    
```


```{r}

#price growth table
updated_data <- read_csv("final_proj/updated_data.csv") 

max_min <- updated_data %>% 
  group_by(ndc_description) %>% 
  summarise(min = min(effective_date), max = max(effective_date))

updated_data_2 <- full_join(updated_data, max_min, by = "ndc_description")

data_13 <- read_csv("final_proj/updated_data.csv") %>% 
  filter(effective_date == 2013)

data_14 <- updated_data_2 %>% 
  filter(max == 2014 & effective_date == 2014)

data_15 <- updated_data_2 %>% 
  filter(max == 2015 & effective_date == 2015)
data_17 <- updated_data_2 %>% 
  filter(max == 2017 & effective_date == 2017)

data_18 <- updated_data_2 %>% 
  filter(max == 2018 & effective_date == 2018)

data_20 <- updated_data_2 %>% 
  filter(effective_date == 2020)



data_13_14 <- inner_join(data_13, data_14, by = "ndc_description")
data_13_15 <- inner_join(data_13, data_15, by = "ndc_description")
data_13_17 <- inner_join(data_13, data_17, by = "ndc_description")
data_13_18 <- inner_join(data_13, data_18, by = "ndc_description")
data_13_20 <- inner_join(data_13, data_20, by = "ndc_description")

merge_1 <- full_join(data_13_14, data_13_15)
merge_2 <- full_join(data_13_17, data_13_18)
merge_3 <- full_join(merge_1, merge_2)
final <- full_join(data_13_20, merge_3)


Price_growth <- final %>% 
  group_by(ndc_description) %>% 
  summarize(avg_rate = (mean_price.y - mean_price.x)/(max - min),
            per_chg = ((mean_price.y - mean_price.x)/mean_price.x)*100)

write.csv(Price_growth,"price_growth.csv")

growth <- read_csv("final_proj/price_growth.csv") %>% 
  select(-X1)

growth %>% 
  gt() %>%
  tab_header(title = "Changes in Prices") %>%
  
  tab_style(style = list(cell_fill(color = "#EF233C"),
                         cell_text()),
            locations = cells_body(columns = vars(per_chg),
                                   rows = per_chg < 0)) %>%
  tab_style(style = list(cell_fill(color = "#C7EFCF"),
                         cell_text()),
            locations = cells_body(columns = vars(per_chg),
                                   rows = per_chg > 0 & per_chg < 17)) %>%
  tab_style(style = list(cell_fill(color = "#88D18A"),
                         cell_text()),
            locations = cells_body(columns = vars(per_chg),
                                   rows = per_chg > 17 & per_chg < 100)) %>% 
  tab_style(style = list(cell_fill(color = "#04724D"),
                         cell_text()),
            locations = cells_body(columns = vars(per_chg),
                                   rows = per_chg > 100)) %>% 
   tab_style(style = list(cell_fill(color = "#EF233C"),
                         cell_text()),
            locations = cells_body(columns = vars(per_chg),
                                   rows = per_chg < -5)) %>%
  tab_style(style = list(cell_fill(color = "#F4796B"),
                         cell_text()),
            locations = cells_body(columns = vars(per_chg),
                                   rows = per_chg < 0 & per_chg > -5)) %>% 
    tab_style(style = list(cell_fill(color = "#04724D"),
                         cell_text()),
            locations = cells_body(columns = vars(avg_rate),
                                   rows = avg_rate > .4)) %>%
   tab_style(style = list(cell_fill(color = "#F4796B"),
                         cell_text()),
            locations = cells_body(columns = vars(avg_rate),
                                   rows = avg_rate < 0)) %>%
  tab_style(style = list(cell_fill(color = "#88D18A"),
                         cell_text()),
            locations = cells_body(columns = vars(avg_rate),
                                   rows = avg_rate > .1 & avg_rate < .4)) %>% 
  tab_style(style = list(cell_fill(color = "#C7EFCF"),
                         cell_text()),
            locations = cells_body(columns = vars(avg_rate),
                                   rows = avg_rate > 0 & avg_rate < .1))
  
  
  
 
ztable(data.frame(growth)) %>% 
  addCellColor(condition = per_chg < 0, cols = per_chg, color="red") 

formattable(growth, align = c("l",rep("r", NCOL(growth))), list(
    ndc_description = formatter("span", style = ~ style(color = "grey",font.weight = "bold")), 
     area(col = 2:3) ~  if_else(growth$per_chg < 0, color_tile("#DeF7E9", "#71CA97"), color_tile("red", "pink"))))
?ztable()

?patchwork()
p1 <- ggplot(mtcars) + geom_point(aes(mpg, disp))
p2 <- ggplot(mtcars) + geom_boxplot(aes(gear, disp, group = gear))

p1 + p2

```


```{r}
# helpful table for all brand plot

tibble(Brand = c("Amoxicillin", "Cozaar", "Glucophage",
                 "Lipitor", "Neurontin", "Norvasc",
                 "Prilosec", "Prinivil", "Synthroid", "Zocor"),
       `Condition Treated` = c("Bacterial infection","Hypertension", "Diabetes",
                               "High cholesterol", "Seizures, Nerve pain",
                               "Hypertension", "Acid reflex/Heartburn, Ulcers",
                               "Hypertension, Heart Failure", "Hypothyroidism",
                               "High cholesterol")) %>% 
  gt() %>% 
  tab_style(style = list(cell_fill(color = "lightblue"),
                         cell_text(weight = "bold")),
            locations = cells_column_labels(columns = vars(Brand, `Condition Treated`))) %>% 
  cols_align(align = "center",
             columns = vars(`Condition Treated`))
```


Model Ideas:

Predict a drug's price using predictors: condition treated, country/healthcare system, producer, # of generic substitutes, and per capita spending 

```{r}
test <- read_excel("test_price_predictor.xlsx") %>% 
  clean_names() %>% 
  pivot_longer(cols = usa_cost:turkey_cost, names_to = "country",
               values_to = "cost")

fit <- stan_glm(data = test, formula = cost ~ country + firm + class + country_produced,
         refresh = 0)

new_obj <- tibble(country = c("usa_cost", "india_cost"), firm = "Pfizer", class = "mental",
                  country_produced = "USA")



posterior_predict(fit, newdata = new_obj) %>% 
  as_tibble() %>% 
   mutate_all(as.numeric) %>% 
   rename(usa = 1, india = 2) %>% 
   pivot_longer(cols = usa:india, names_to = "country",
                values_to = "cost") %>% 
  ggplot(aes(cost, fill = country)) +
    geom_histogram(aes(y = after_stat(count/sum(count))),bins = 100)

```

```{r}
# trends by therapeutic class

expend_by_class <- read.csv("total_expenditure_by_class.csv") %>% 
  clean_names() %>% 
  pivot_longer(cols = -therapeutic_class, names_to = "year",
               values_to = "expenditure") %>% 
   mutate(year = as.numeric(str_sub(year, 2L)))

purchase_by_class <- read.csv("total_purchases_by_class.csv") %>% 
  clean_names() %>% 
  pivot_longer(cols = -therapeutic_class, names_to = "year",
               values_to = "purchases") %>% 
   mutate(year = as.numeric(str_sub(year, 2L)))
  

therapeutic_classes <-full_join(expend_by_class, purchase_by_class, by = c("therapeutic_class", "year"))

therapeutic_classes <- write.csv(therapeutic_classes, file = "therapeutic_classes.csv")

therapeutic_classes_final <- read_csv("final_proj/therapeutic_classes.csv")

therapeutic_list <- therapeutic_classes_final %>% 
    pull(therapeutic_class) %>% 
    unique()

therapeutic_classes_final %>% 
  filter(therapeutic_class %in% therapeutic_list) %>% 
  group_by(therapeutic_class, year) %>% 
  summarize(expend_per_purchase = log((expenditure*1000000)/(1000*purchases))) %>% 
  drop_na() %>% 
  ggplot(aes(year, expend_per_purchase, color = therapeutic_class)) +
    geom_line() +
    theme(legend.title = element_text(size = 5), 
          legend.text = element_text(size = 5),
          legend.position = "bottom") + 
   stat_summary(fun.y=mean, aes(group=1), geom="line", colour="darkblue", size = 1.2, lty = 3) +
  theme_clean()


  therapeutic_classes_final %>%
            rename(`Therapeutic Class` = therapeutic_class) %>% 
            drop_na() %>% 
            # filter(`Therapeutic Class` %in% input$select_class,
            #        year %in% input$select_year) %>%
            group_by(`Therapeutic Class`, year) %>% 
            summarize(expend_per_purchase = log((expenditure*1000000)/(1000*purchases))) %>% 
            ggplot(aes(x = year, y = expend_per_purchase, color = `Therapeutic Class`)) +
            geom_line() +
            stat_summary(fun.y=mean, aes(group = 1), geom="line", colour="darkblue", size = 1.2, lty = 3) +
            labs(title = "Log Expenditure per Purchase by Therapeutic Class",
                 x = "Year",
                 y = "Log Expenditure per Purchase") +
            theme_clean() +
            theme(legend.title = element_text(size = 6), 
                  legend.text = element_text(size = 6),
                  legend.position = "right") 

```

```{r}
international <- read_excel("final_proj/Lowest_Price_Per_Unit_for_Top_200_drugs.xlsx") %>% 
  clean_names() %>% 
  group_by(drug_name) %>% 
  filter(price_per_unit == min(price_per_unit)) %>% 
  select(drug_name, price_per_unit, country, strength) %>% 
  mutate(region = "International")

write_csv(international,file = "international_prices.csv")
  
international %>% 
  select(drug_name, strength)

final_set <- read_csv("final_proj/international_prices.csv") %>% 
  clean_names() %>% 
  pivot_longer(cols = c("int_price_per_unit", "usa_price_per_unit"),
               names_to = "location", values_to = "price") %>% 
  select(drug_name, condition, type, total_options, num_subs, price, location) 

fit_model <- stan_glm(formula = price ~ type + num_subs + location,
         data = final_set, refresh = 0)

  
tbl_regression(fit_model, intercept = T) %>% 
  as_gt() %>% 
  tab_header(title = "Regression of Drug Prices" ,
             subtitle = "The Effect of Various Predictors on Prices") %>% 
  tab_source_note(md("Source: PharmacyChecker & Good Rx"))

obj <- tibble(type = c("brand", "generic"),
              num_subs = 1, location = "usa_price_per_unit")
  
predict <- posterior_predict(fit_model, newdata = obj) %>% 
  as_tibble() %>% 
   mutate_all(as.numeric) %>% 
   rename(brand = 1, generic = 2)

brand_mean <- mean(predict$brand)
generic_mean <- mean(predict$generic)

predict %>% 
   pivot_longer(cols = brand:generic, names_to = "type",
                values_to = "cost") %>% 
  ggplot(aes(cost, fill = type)) +
    geom_histogram(aes(y = after_stat(count/sum(count))),bins = 100) +
    geom_vline(xintercept = brand_mean, lty = 2) +
    geom_vline(xintercept = generic_mean, lty = 2,
               color = "purple") +
    labs(title = "Predicted Average Cost for Brand vs Generic \n",
         x = "Average Cost",
         y = "Probability") +
    theme_minimal() +
     scale_fill_manual(values = c("coral", "green"), 
                      labels = c("Generic", "Brand"),
                      name = "Type")

obj_2 <- tibble(type = "brand",
              num_subs = 1, location = c("usa_price_per_unit", "int_price_per_unit"))
              
predict_2 <- posterior_predict(fit_model, newdata = obj_2) %>% 
  as_tibble() %>% 
   mutate_all(as.numeric) %>% 
   rename(usa = 1, international = 2) 

usa_mean <- mean(predict_2$usa)
int_mean <- mean(predict_2$international)

predict_2 %>% 
   pivot_longer(cols = usa:international, names_to = "location",
                values_to = "cost") %>% 
  ggplot(aes(cost, fill = location)) +
    geom_histogram(aes(y = after_stat(count/sum(count))),bins = 100) +
    geom_vline(xintercept = usa_mean, lty = 2,
               color = "white") + 
    geom_vline(xintercept = int_mean, lty = 2,
               color = "red") + 
    labs(title = "Predicted Average Cost for International vs US Bought \n",
         x = "Average Cost", y = "Probability") +
    theme_minimal() +
    scale_fill_manual(values = c("pink", "dodgerblue"), 
                      labels = c("International", "US"),
                      name = "Location")


obj_3 <- tibble(type = "brand",
              num_subs = c(1,2,3), location = "usa_price_per_unit")

predict_3 <- posterior_predict(fit_model, newdata = obj_3) %>% 
  as_tibble() %>% 
  mutate_all(as.numeric) %>% 
  rename(one = 1, two = 2, three = 3) 

one_mean <- mean(predict_3$one)
two_mean <- mean(predict_3$two)
three_mean <- mean(predict_3$three)

predict_3 %>% 
   pivot_longer(cols = c(one, two, three), names_to = "Subs",
                values_to = "cost") %>% 
  ggplot(aes(cost, fill = Subs)) +
    geom_histogram(aes(y = after_stat(count/sum(count))),bins = 100) +
    geom_vline(xintercept = one_mean, lty = 1,
               color = "green") + 
    geom_vline(xintercept = two_mean, lty = 2,
               color = "purple") +
    geom_vline(xintercept = three_mean, lty = 3,
               color = "brown") +
    labs(title = "Predicted Average Costs for Varying Number of Drug Alternatives \n" ,
         x = "Average Cost", y = "Probability") +
    theme_minimal() +
    scale_fill_manual(values = c("coral", "green", "blue"), 
                      labels = c("one", "two", "three"),
                      name = "Alternative")

tibble(Alternatives = 1:3, `Average Cost ($)` = c(one_mean, two_mean, three_mean))
  


```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
